import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const noirEtBlanc = localFont({
  src: [
    {
      path: "../public/fonts/NOIRetBLANC-Regular.ttf",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-noir", // create a CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noirEtBlanc.variable}>
      <body>{children}</body>
    </html>
  );
}
